name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Start Backend
      run: npm run start-be &
    - name: Wait for the process to start
      run: sleep 5
    - name: Start Frontend
      run: npm run start-fe &
    - name: Wait for the process to start
      run: sleep 5
    - name: Run tests
      run: npm run test

  deploy-backend:
    needs: build-and-test    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
      - name: Wait for the Backend service to start
        run: sleep 120

  deploy-frontend:
    needs: deploy-backend    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_FRONTEND_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}      